### ISSUE TITLE
Undefined reference to `main'

### ISSUE THREAD

**Issue by samuelfusato** [benhoyt/ht#2]
Dear colleagues,

I am receiving the following error when compiling this program:

```
sles15-sp3-sca:~/hashtable # gcc ht.c -o ht
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64/crt1.o: in function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
```

Can you kindly verify? Thank you.

**Comment by benhoyt** [comment]
Hi @samuelfusato. Yes, this is expected, because `ht.c` is a library and not a complete program -- it doesn't define `main`. You can use the `-c` flag to compile it to an object file, like so:

```
$ gcc -c ht.c
$ file ht.o
ht.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

Or you can build a full program, like the `samples/demo.c` program, like so:

```
$ gcc -Wall -O2 -o demo samples/demo.c ht.c
$ echo the foo foo foo | ./demo
foo 3
the 1
2
```

Hope that helps!
