### ISSUE TITLE
"ht_iterator" returns the address of a variable allocated in the stack

### ISSUE THREAD

**Issue by tappara** [benhoyt/ht#3]
The iterator has an issue, "ht_iterator" returns the address of a variable allocated in the stack, so when it goes out of scope it becomes invalid.

Nice work though. 

Cheers, 
Nicola

**Comment by benhoyt** [comment]
Hi @tappara, I think you'll find `ht_iterator` returns a value -- a copy of the `hti` struct on the stack, not a pointer to it. If it was `return &it` that would be returning a pointer to a local variable.
