### ISSUE TITLE
Redundant key comparison when expanding table?

### ISSUE THREAD

**Issue by tenko** [benhoyt/ht#4]
Coming here from reading you excellent article and trying to implement this in Oberon-2.

I was wondering when the table expands there should not be any duplicate keys and
therefore the line: `if (strcmp(key, entries[index].key) == 0) {` in `ht_set_entry` is not needed.

We can just skip to next free slot?
Do I think right here?

**Comment by benhoyt** [comment]
For reference, [here's a link to the line of code](https://github.com/benhoyt/ht/blob/30e515dfd40e2e0df0def630150ad449ed8a0684/ht.c#L98) you're referring to.

You're right there will never be duplicate keys, but here we're starting the index at the hash slot and looping till either we find an empty slot (the `while (entries[index].key != NULL)`) or we find that the key is already present in the map (the line you mentioned). So this line of code is needed in case the key is already present in the map, in which case we just update its value.

Hope that helps!

**Comment by tenko** [comment]
Thanks for the clarification.
