### ISSUE TITLE
Support for int as key type

### ISSUE THREAD

**Issue by olleharstedt** [benhoyt/ht#6]
Hi!

Thanks for your great implementation and explanation! I have a quick question: It seems like this hash table does not support keys of type int (or long, etc)? So key type is only `char*`, correct? Would it be hard to expand to support different key types?

Regards
Olle

**Comment by benhoyt** [comment]
No, it doesn't support other types directly, just NUL-terminated `char*` strings. It wouldn't be hard to pass a size with each key so it could be an arbitrary pointer to bytes of a given length. Then you could pass a pointer to an int or float or whatever. I'm not sure whether the FNV hash is still good for arbitrary binary bytes including zeros (maybe? you'd have to do some research).

I'd rather not adjust this repo, as it's for educational purposes (to go with my article), but you're welcome to fork this repo and make this change in your fork!
