### ISSUE TITLE
About overflow check in bsearch.c, Maybe it's a bug

### ISSUE THREAD

**Issue by liweiyuan** [benhoyt/ht#7]
if (size + size < size) {
        return NULL; // size too big; avoid overflow
 }

Maybe:
 if (size > SIZE_MAX / 2) {
    return NULL; // size too big; avoid overflow
}

**Comment by benhoyt** [comment]
That would probably work too, but what I have is correct (I didn't know about the constant, or didn't want to use it, I'm not sure anymore). If an unsigned integer is more than half of SIZE_MAX it will overflow and wrap to a smaller number.
